# Generated by Django 4.1.7 on 2023-05-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
